sudo: required
services:
   - docker
#testing phase
before_install: 
   - docker build -t ScottMureti/react-test -f ./client/Dockerfile.dev ./client #path of the dockerfile its on the client folder

script:
   - docker run -e CI=true ScottMureti/react-test npm test -- --coverage --watchAll=false

#build for the production
after_success: 
   - docker build -t martin/multi-client ./client #we dont have to specify the file, will use default file, Dockerfile
   #do the same for the other folders
   - docker build -t ScottMureti/multi-nginx ./nginx
   - docker build -t ScottMureti/multi-server ./server
   - docker build -t ScottMureti/multi-worker ./worker
 #Log in to the docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
   - docker push ScottMureti/multi-client
   - docker push ScottMureti/multi-nginx
   - docker push ScottMureti/multi-server
   - docker push ScottMureti/multi-worker

